name       : alacarte
version    : 3.44.3
release    : 10
source     :
    - https://download.gnome.org/sources/alacarte/3.44/alacarte-3.44.3.tar.xz : 0101ec51cfb11958e3a6e0a3a22707c20050bb29ae0ffedff33947a5745a91b6
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : GNOME Menu Editor
description: |
    GNOME Graphical Menu Editor
builddeps  :
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
rundeps    :
    - libgnome-menus
    - python-gobject
setup      : |
    %configure --disable-documentation
build      : |
    %make
install    : |
    %make_install
