name       : alacarte
version    : 3.11.91
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/alacarte/3.11/alacarte-3.11.91.tar.xz : d77294f25ac9e4f293530080578d83dc8e014d5b7c6c01d6f9a7f1715719a384
license    : GPL-2.0
summary    : GNOME Menu Editor
description: |
    GNOME Graphical Menu Editor
builddeps  :
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
rundeps    :
    - python3-gobject
setup      : |
    %configure --disable-documentation
build      : |
    %make
install    : |
    %make_install
