name       : alacarte
version    : 3.44.1
release    : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/alacarte/3.44/alacarte-3.44.1.tar.xz : 5371597930fedf2c8346668550ac3c13baf1dd6455440fc8fdd67eb55c6fd38c
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : GNOME Menu Editor
description: |
    GNOME Graphical Menu Editor
builddeps  :
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
rundeps    :
    - libgnome-menus
    - python-gobject
setup      : |
    %configure --disable-documentation
build      : |
    %make
install    : |
    %make_install
