name       : alacarte
version    : 3.36.0
release    : 7
source     :
    - http://ftp.gnome.org/pub/gnome/sources/alacarte/3.36/alacarte-3.36.0.tar.xz : 5c1e09a8926ac77a049b199c97ac459f98a65816041feb392c839a91edc8e75d
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : GNOME Menu Editor
description: |
    GNOME Graphical Menu Editor
builddeps  :
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
rundeps    :
    - libgnome-menus
    - python-gobject
setup      : |
    %configure --disable-documentation
build      : |
    %make
install    : |
    %make_install
